### ISSUE TITLE
Connecting with leeshan

### ISSUE THREAD

**Issue by anupam19** [ARMmbed/mbed-client-linux-example#12]
Hi, I had tried to connect with leeshan server and it created test resources. 

```C++
    bool create_generic_object() {
        bool success = false;
        _object = M2MInterfaceFactory::create_object("16");
        if(_object) {
            M2MObjectInstance* inst = _object->create_object_instance();
            if(inst) {
                M2MResource* res = inst->create_dynamic_resource("1",
                                                                 "ResourceTest",
                                                                 M2MResourceInstance::INTEGER,
                                                                 false);
                char buffer[20];
                int size = sprintf(buffer,"%d",_value);
                  res->set_operation(M2MBase::GET_PUT_ALLOWED);
                  res->set_value((const uint8_t*)buffer,
                                 (const uint32_t)size);
                  res->set_execute_function(execute_callback(this,&MbedClient::execute_function));
                _value++;
                inst->create_static_resource("4",
                                             "ResourceTest",
                                             M2MResourceInstance::STRING,
                                             STATIC_VALUE,
                                             sizeof(STATIC_VALUE)-1);
            }
        }
        return success;
    }
```

From leeshan server I tried to read write and observe values sent from this client but it says timeout. My server is localhost so no network issue. 
Also the client shows error
Sending update register

Error occured Error Code : 10.
Can you please clarify what is happening ?
![screenshot-localhost 8080 2015-10-02 13-41-55](https://cloud.githubusercontent.com/assets/8350647/10242049/875d2f5e-690b-11e5-818f-bcd4594e8861.png)

**Comment by yogpan01** [comment]
Can you check on the wireshark as to what is happening to the traffic between your client and server ?
Looks like the client is not able to send even the register update message to the server. Hence , error 10 (check M2MInterface::Error for error code mapping)

**Comment by anupam19** [comment]
Wireshark analysis result shows that it's a bad request. source port is a random generated as I see every time (41928) and destination is 5683

**Comment by yogpan01** [comment]
Which request is a bad request? Registration or Register Update ? This client still follows old spec of Update register as PUT . Not sure if the leeshan server is expecting POST as register update request.

**Comment by anupam19** [comment]
Update Register shows Bad request 4.00.
Client log : 
$ ./mbed-client-linux-example 
Endpoint Name : anupam99

Interface created
register object created
Device object created !!
Registering endpoint

Registered
Sending observation
Flag 1Resource Value /16/0/1 : 1
Flag 2Flag 3Sending update register

Error occured Error Code : 3
^C
Unregistering endpoint and EXITING Program

Error occured Error Code : 10

**Comment by yogpan01** [comment]
Hi,
It looks like the Leeshan server you are using has removed the PUT support for update-register.
mbed-client stil sends PUT as part of update-register, we will try to update that change soon. In the meantime, you can proceed by commenting out following lines from your test application.

//pthread_create(&update_register_thread, NULL, &update_register, (void*) &mbed_client);
//pthread_join(update_register_thread, NULL);
//pthread_detach(update_register_thread);

**Comment by anupam19** [comment]
I tried to read values sent by client to leshan server [GET request from server]. the reply was NOT_FOUND.

**Comment by yogpan01** [comment]
Which resource are you trying to read from server(issue GET) ? Again , can you check from Wireshark what response are you getting from client for your GET request ?

**Comment by mjkoster** [comment]
If you don’t update the registration, it will expire after the number of seconds configured by the “lt” registration parameter. After expiration, the device server (Leshan) should not send any requests to the client.

Michael

**Comment by anupam19** [comment]
From leshan to mbed client the GET request got timed out everytime. Wireshark shows CON but no ACK in client.

**Comment by anupam19** [comment]
@mjkoster I had set lifetime as 3600 so should not be a problem

**Comment by yogpan01** [comment]
I am suspecting that your UDP port might be blocked by some network firewall which is preventing 2- way communication.

**Comment by anupam19** [comment]
I am doing it in localhost and no firewall is set

```C
    bool create_interface() {

       time_t t;
       srand((unsigned) time(&t));

       uint16_t port = 5683; //rand() % 65535 + 12345;

        _interface = M2MInterfaceFactory::create_interface(*this,
                                                  ENDPOINT_NAME,
                                                  "test",
                                                  3600,
                                                  port,
                                                  MBED_USER_NAME_DOMAIN,
                                                  M2MInterface::UDP,
                                                  M2MInterface::LwIP_IPv4,
                                                  "");
        printf("Endpoint Name : %s\n", ENDPOINT_NAME.c_str());
        return (_interface == NULL) ? false : true;
    }
```

Can you tell me uint16_t port = 5683; //rand() % 65535 + 12345; is that the listening port ?ie. destination port for leshan server if I send GET request from leshan

**Comment by yogpan01** [comment]
Yes , that's the listening port. So, Is your registration POST going fine and is the client receiving ACK for that correctly. 
Are you seeing below logs on your linux application console ? 
```Interface created
register object created
Device object created !!
Registering endpoint

Registered
```

**Comment by anupam19** [comment]
Yes, registration is OK. But while I do GET from leshan, it shows src port 5683 and destination port something other than 5683 and there is no ACK. There is no log in wireshark for send observation as well.

**Comment by anupam19** [comment]
Additional log :

./mbed-client-linux-example 
Endpoint Name : anupam099

Interface created
register object created
Device object created !!
Registering endpoint

Registered
Sending observation
Resource Value /16/0/1 : 1
Sending update register

Error occured Error Code : 3
Sending observation
Resource Value /16/0/1 : 2
Sending observation
Resource Value /16/0/1 : 3
Sending update register

Error occured Error Code : 10
Sending observation
Resource Value /16/0/1 : 4
^C
Unregistering endpoint and EXITING Program

Error occured Error Code : 10

Sequence in Wireshark:

1358	4903.520479000	127.0.0.1	127.0.0.1	CoAP	318	CON, MID:468, POST, /rdep=anupam099et=testlt=3600d=domainb=U?&&&& (text/plain)
User Datagram Protocol, Src Port: 53290 (53290), Dst Port: 5683 (5683)

1367	4903.524043000	127.0.0.1	127.0.0.1	CoAP	60	ACK, MID:468, 2.01 Created
User Datagram Protocol, Src Port: 5683 (5683), Dst Port: 53290 (53290)

1371	4923.521936000	127.0.0.1	127.0.0.1	CoAP	74	CON, MID:469, PUT, /rd/domain/anupam099lt=3600?
User Datagram Protocol, Src Port: 53290 (53290), Dst Port: 5683 (5683)

1372	4923.522428000	127.0.0.1	127.0.0.1	CoAP	46	ACK, MID:469, 4.00 Bad Request
User Datagram Protocol, Src Port: 5683 (5683), Dst Port: 53290 (53290)

And there is no log for observation send

**Comment by anupam19** [comment]
Hi @yogpan01 have you seen the log I have posted ? let me know your view

**Comment by yogpan01** [comment]
Hi, I see you are still using the update register functionality. How about if you remove this part 
//pthread_create(&update_register_thread, NULL, &update_register, (void*) &mbed_client);
//pthread_join(update_register_thread, NULL);
//pthread_detach(update_register_thread);

We will be soon updating our library to support update register . 
In the meantime, please try commenting out the update register part and let me know if there is any progress.

**Comment by anupam19** [comment]
![screenshot from 2015-10-07 11 13 46](https://cloud.githubusercontent.com/assets/8350647/10329892/96f7f778-6ce4-11e5-8173-5888399888f2.png)

This is the log for GET from Leshan in wireshark. There is nothing for Send observation.
Also in Leshan web UI the coap msg log says
11:17:14.371	 CON-GET	64317	7971f190	Uri-Path: 3, 0, 2, 16, 0, 1
But the URI path according to mbed client  is : [see log]
Endpoint Name : anupam099

Interface created
register object created
Device object created !!

Generic object created
Registering endpoint

Registered
Sending observation
Resource Value /16/0/1 : 1
Sending observation
Resource Value /16/0/1 : 2
Sending observation
Resource Value /16/0/1 : 3
Sending observation
Resource Value /16/0/1 : 4
Sending observation
Resource Value /16/0/1 : 5
Sending observation
Resource Value /16/0/1 : 6
Sending observation
Resource Value /16/0/1 : 7
Sending observation
Resource Value /16/0/1 : 8

**Comment by yogpan01** [comment]
The reason there is no Send Observation seen on Wireshark is because sending observation mainly works for observing resource which is subscribed by some web service , in this case there is no web service subscribed to this resource so it is only updating the observation locally but not sending any notification, We will be releasing soon example web-app where this resource will be automatically subscribed and then you can see the value going through wireshark.

**Comment by anupam19** [comment]
The leshan server has an observe button through which it can sub that publisher. That too reports as NOT_FOUND
![screenshot-localhost 8080 2015-10-07 11-46-56](https://cloud.githubusercontent.com/assets/8350647/10330319/3465e296-6ce9-11e5-9be4-524660661be7.png)

**Comment by yogpan01** [comment]
May be this is the issue 
  M2MResource* res = inst->create_dynamic_resource("1",
                                                                 "ResourceTest",
                                                                 M2MResourceInstance::INTEGER,
                                                                 false);

try to pass "true" instead of "false" as parameter, this defines whether the resource is observable or not.

**Comment by anupam19** [comment]
It's already true in my case :
```C
                M2MResource* res = inst->create_dynamic_resource("1",
                                                                 "ResourceTest",
                                                                 M2MResourceInstance::INTEGER,
                                                                 true,
                                                                 false);
```

**Comment by anupam19** [comment]
If you want to see what's happening with leshan you can try this out :
wget https://hudson.eclipse.org/leshan/job/leshan/lastSuccessfulBuild/artifact/leshan-standalone.jar
java -jar ./leshan-standalone.jar

**Comment by yogpan01** [comment]
I will take a look into this and let you know.

**Comment by anupam19** [comment]
ok @yogpan01

**Comment by anupam19** [comment]
Hi @yogpan01 have you tested that leshan server with mbed-linux-example ? Let me know what you got.

**Comment by rainierwolfcastle** [comment]
http://jira-dev0.cambridge.arm.com/browse/IOTCLT-271

**Comment by yogpan01** [comment]
Hi @anupam19 I planned to check it early this week but didn't get time. This is surely on my list and I will check it soon . Sorry for the delay.

**Comment by anupam19** [comment]
@yogpan01 sure. waiting :)

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTCLT-360

**Comment by anupam19** [comment]
@rainierwolfcastle What was that ?

**Comment by yogpan01** [comment]
@anupam19 This is an internal reference number for tracking the issue.

**Comment by yogpan01** [comment]
Hi @anupam19 I checked the leshan server and I also get the same issue when trying to read the resource but I see problem in the CoAP requests coming from Leshan server , as you can also see in your attached Wirseshark trace, the request is coming to wrong URI "/3/0/2/3/16/0" so client doesn't have any such resource. For some reason Leshan server is prefixing "/3/0/2" in front of the proper resource. I think this is a bug on Leshan server end as it is not complying with the registered resource format.
We will be soon releasing the Device Connector service against which you can test the mbed-client.

**Comment by yogpan01** [comment]
@anupam19 We have fixed this issue now. mbed-client will now handle the GET request from the Leshan server. We will release the updated patch soon. I will update this issue when we release the fix.

**Comment by anupam19** [comment]
Hi @yogpan01 Have you already updated the patch?

**Comment by yogpan01** [comment]
Hi @anupam19 Can you try it now ? Check out the latest version and then try.

**Comment by anupam19** [comment]
It shows
```C
Interface created
register object created
Device object created !!
Registering endpoint

Error occured  : M2MInterface::NetworkError
```

**Comment by anupam19** [comment]
Also I am seeing the non secure mode is removed from the current release.

**Comment by yogpan01** [comment]
Hi, This example only support Secure Connectivity and works against Device Connector Service . However, we still have non-secure support, but you will need to modify your code to support Non-secure mode.

**Comment by anupam19** [comment]
Is it supporting PSK ? @yogpan01

**Comment by yogpan01** [comment]
Yes, It supports .

**Comment by yogpan01** [comment]
Device Connector Service is now live , check out connector.mbed.com for further testing.
