### ISSUE TITLE
Display more information when an error is shown

### ISSUE THREAD

**Issue by mlnx** [ARMmbed/mbed-client-linux-example#13]
When running mbed-client-linux-example under Linux/Ubuntu, I hit this error (I don't care about the real reason behind it)

```Error occured Error Code : 3```

We should add more information for every error reported. A simple number does not help! ;)

**Comment by simonqhughes** [comment]
ARM Internal Ref: IOTCLT-369

**Comment by yogpan01** [comment]
Fix is now available. Checkout the latest TechCon-release branch for verification.

**Comment by mlnx** [comment]
Validated latest version. Works ok.
