### ISSUE TITLE
In Disclaimer Section, link to ARM MBED Connector web does not work

### ISSUE THREAD

**Issue by hasnainvirk** [ARMmbed/mbed-client-linux-example#17]
Please correct the link in Disclaimer section.  

Link to ARM mbed Connector website ends up in Server not found.

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTCLT-387

**Comment by yogpan01** [comment]
Disclaimer is there to inform developers about the upcoming website, its not yet live but it will go live when this disclaimer will be released to master branch. Closing this issue.
