### ISSUE TITLE
Still very unstable. Does not connect/Connects with Error codes

### ISSUE THREAD

**Issue by hasnainvirk** [ARMmbed/mbed-client-linux-example#19]
Setup: Linux
target: x86-linux-native
Comment: I took a new clone and changed the branch to TechCon-release. 
Issue: Very unstable.  Sometimes gets registered with Connector after removing cookies. Sometimes does not even register.
  
TRACE
hasnain@ubuntu:~/Desktop/OOB2/mbed-client-linux-example/build/x86-linux-native/source$ ./mbed-client-linux-example 
Endpoint Name : 8ed00fc2-fc52-4b49-a0c0-8069f06f1cca

Interface created
register object created
Device object created !!
Registering endpoint

Error occured Error Code : 6

Error occured Error Code : 6

Registered

Error occured Error Code : 6

Error occured Error Code : 6
Incrementing Resource Value
Resource Value /Test/0/D : 1

Error occured Error Code : 6

Error occured Error Code : 6
Sending update register

Error occured Error Code : 10
Incrementing Resource Value
Resource Value /Test/0/D : 2
^C

**Comment by hasnainvirk** [comment]
I took a new clone and changed the branch to TechCon-release.

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTCLT-386

**Comment by yogpan01** [comment]
Not valid. This code is not even on TechCon-release branch. Please use TechCon-release branch for testing.
