### ISSUE TITLE
Does not connect to the device connector

### ISSUE THREAD

**Issue by hasnainvirk** [ARMmbed/mbed-client-linux-example#20]
!! I am dead sure that I checked out to TechCon release branch
I!! I am dead sure that I cleared the cookies from the browser
!! I am dead sure that my VM is in 'Bridge Mode'

It just does not work.

hasnain@ubuntu:~/Desktop/OOB2/mbed-client-linux-example/build/x86-linux-native/source$ sudo ./mbed-client-linux-example 
[sudo] password for hasnain: 
Endpoint Name : cd71d7b4-833e-49f4-8a64-cb96733d7ebd

Interface created
register object created
Device object created !!
Registering endpoint

Error occured Error Code : 6

Error occured Error Code : 6

Registered

Error occured Error Code : 6

Error occured Error Code : 6
Incrementing Resource Value
Resource Value /Test/0/D : 1

Error occured Error Code : 6

Error occured Error Code : 6
Sending update register

Error occured Error Code : 10
Incrementing Resource Value
Resource Value /Test/0/D : 2
Incrementing Resource Value
Resource Value /Test/0/D : 3

Error occured Error Code : 6

Error occured Error Code : 6
Sending update register

Error occured Error Code : 10
Incrementing Resource Value
Resource Value /Test/0/D : 4
Incrementing Resource Value
Resource Value /Test/0/D : 5
Sending update register

Error occured Error Code : 10
Incrementing Resource Value
Resource Value /Test/0/D : 6
Incrementing Resource Value
Resource Value /Test/0/D : 7
Sending update register

Error occured Error Code : 10
Incrementing Resource Value
Resource Value /Test/0/D : 8
Incrementing Resource Value
Resource Value /Test/0/D : 9
Sending update register

Error occured Error Code : 10
Incrementing Resource Value
Resource Value /Test/0/D : 10
Sending update register

Error occured Error Code : 10
Incrementing Resource Value
Resource Value /Test/0/D : 11
Incrementing Resource Value
Resource Value /Test/0/D : 12
^C
Unregistering endpoint and EXITING Program

Error occured Error Code : 10
hasnain@ubuntu:~/Desktop/OOB2/mbed-client-linux-example/build/x86-linux-native/source$

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-388

**Comment by hasnainvirk** [comment]
Made it working. Had to fetch and pull from the TechCon-Release branch.
