### ISSUE TITLE
pthread_cancel called with zero as argument

### ISSUE THREAD

**Issue by vanti** [ARMmbed/mbed-client-linux-example#33]
In threadhelper.cpp, ~ThreadHelper() calls pthread_cancel() even when _thread_id is 0 and invalid. Suggest to make sure _thread_id is not zero before calling pthread_cancel(), as has been done in ThreadHelper::cancel().

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-594

**Comment by anttiylitokola** [comment]
Hi,
Thanks for your finding.
This is now resolved in following PR:
https://github.com/ARMmbed/mbed-client-linux/pull/29
