### ISSUE TITLE
Bootstrap support in mbed-client-linux-example

### ISSUE THREAD

**Issue by phtrivier** [ARMmbed/mbed-client-linux-example#44]
Hi

 I'm trying to get modify mbed-client-linux-example to use bootstraping.
 I'm currently trying to bootstrap against [leshan](https://github.com/eclipse/leshan/tree/master/leshan-bsserver-demo).

I managed to initiate the bootstrap by creating a new Security object : 
~~~
_bs_security = M2MInterfaceFactory::create_security(M2MSecurity::Bootstrap);
 _bs_security->set_resource_value(M2MSecurity::M2MServerUri, BS_SERVER_ADDRESS);
_bs_security->set_resource_value(M2MSecurity::BootstrapServer, 1);
_bs_security->set_resource_value(M2MSecurity::SecurityMode, M2MSecurity::NoSecurity);
~~~

And I start the bootstraping with way : 

~~~
void test_bootstrap() {
    if(_interface) {
      _interface->bootstrap(_bs_security);
    } else {
      printf("Interface doesn't exist, exiting!!\n");
      exit(1);
    }
  }
~~~

During the Bootstrap process, the server sends a DELETE  CoAP message with : 

* Version 1
* Type : Confirmable (0)
* Token Length : 4
* Code : DELETE (4)

The messages goes through : 

* M2MInterfaceImpl::state_coap_data_received
* M2MNdslInterface::process_received_data
* sn_ndsl_process_coap

It seems like the is parsed properly (`coap_packet_ptr->msg_code` is 4), but `coap_packet_ptr->content_type_len` is 0, and so the `sn_ndsl_process_coap` returns an error.

Is `process_received_data` supposed to handle DELETE during Boostrap process ?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-827

**Comment by yogpan01** [comment]
Bootstrap support should now be available.
