### ISSUE TITLE
How do you enable mbed-trace

### ISSUE THREAD

**Issue by mark-blackburn-etcorp** [ARMmbed/mbed-client-linux-example#52]
I had to modify yotta_modules/mbed-trace/mbed-trace/mbed_trace.h to set the MBED_CONF_MBED_TRACE_ENABLE define to 1 in order to get tracing to work. Otherwise none of the object files get compiled with tracing support. Is there a better way so that I don't have to modify the mbed source tree?

yotta_modules/mbed-trace/mbed-trace/mbed_trace.h:
```
-#define MBED_CONF_MBED_TRACE_ENABLE 0
+#define MBED_CONF_MBED_TRACE_ENABLE 1
```

The readme at https://github.com/ARMmbed/mbed-trace#prerequisites suggests that you either modify a .json file or set a define for yotta.

**Comment by teetak01** [comment]
Hi, if you compile the application with `yotta build -d mbed-client-linux-example` it should work fine. Its important to specify the module name also there, otherwise it tries to build some unrelated dependencies too.

**Comment by mark-blackburn-etcorp** [comment]
Thanks, that worked.

**Comment by teetak01** [comment]
I'll close this issue as resolved.
