### ISSUE TITLE
example not compiling under Ubuntu 16.04

### ISSUE THREAD

**Issue by jflynn129** [ARMmbed/mbed-client-linux-example#56]
Following the instructions, when executing **yotta target x86-linux-native**
response is:

info: get versions for x86-linux-native
From cffi callback <function _verify_callback at 0x7f5942e13aa0>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 313, in wrapper
    _lib.X509_up_ref(x509)
**AttributeError: 'module' object has no attribute 'X509_up_ref'**
warning: connection error: HTTPSConnectionPool(host='registry.yottabuild.org', port=443): Max retries exceeded with url: /targets/x86-linux-native/versions (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),)), retrying...
From cffi callback <function _verify_callback at 0x7f5942e13b18>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 313, in wrapper
    _lib.X509_up_ref(x509)
**AttributeError: 'module' object has no attribute 'X509_up_ref'**
warning: connection error: HTTPSConnectionPool(host='registry.yottabuild.org', port=443): Max retries exceeded with url: /targets/x86-linux-native/versions (Caused by SSLError(SSLError("bad handshake: **Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),)), retrying...**
From cffi callback <function _verify_callback at 0x7f5942e13b18>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 313, in wrapper
    _lib.X509_up_ref(x509)
**AttributeError: 'module' object has no attribute 'X509_up_ref'**
warning: connection error: HTTPSConnectionPool(host='registry.yottabuild.org', port=443): Max retries exceeded with url: /targets/x86-linux-native/versions (Caused by SSLError(SSLError("bad handshake: **Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),)), retrying...**
From cffi callback <function _verify_callback at 0x7f5942e13b90>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 313, in wrapper
    _lib.X509_up_ref(x509)
**AttributeError: 'module' object has no attribute 'X509_up_ref'**
warning: connection error: HTTPSConnectionPool(host='registry.yottabuild.org', port=443): Max retries exceeded with url: /targets/x86-linux-native/versions (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),)), retrying...
From cffi callback <function _verify_callback at 0x7f5942e13c80>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 313, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
**error: connection error: HTTPSConnectionPool(host='registry.yottabuild.org', port=443): Max retries** exceeded with url: /targets/x86-linux-native/versions (Caused by SSLError(SSLError("bad handshake: **Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
error: tuple index out of range**

What is the problem with the example?

**Comment by teetak01** [comment]
Which version of yotta do you have? The latest should have fixed issues with this.

https://github.com/ARMmbed/yotta/pull/820

So 0.18.4 should be fine.

**Comment by jflynn129** [comment]
I investigated this issue further and found the fix.  You have to install pyopenssl (sudo -H pip install pyopenssl) for this to work.  This is not listed as a requirement in the "Required software and setup" section and is obviously a mistake that should be fixed.
